# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Alexis Werestchack
email: alexis.werestchack@gmail.com
description: >-
  I am a Master’s student in Public Policy and Human Development at Maastricht University,
  with a keen interest in poverty reduction, labor market policies, and humanitarian aid,
  particularly in conflict zones. While my academic work focuses on understanding and
  addressing complex social and economic challenges, I also enjoy exploring the intersection
  of policy and technology. This GitHub repository serves as a space to showcase my coding
  projects, data analysis work, and any tools or resources I develop related to public policy
  research. Here, you'll find examples of my technical skills, including data visualization,
  statistical analysis, and programming applications tailored to policy-related issues.
  Feel free to explore my projects, collaborate, or reach out if you share similar interests!

# URL settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. https://example.com

# Social media usernames
github_username: AlexisWck
linkedin: "https://www.linkedin.com/in/alexis-werestchack-8b599919b"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
